services:
  web:
    build: .
    command: uvicorn FutureFish.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/future_fish
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=FutureFish.settings
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - future_fish_network

  worker:
    build: .
    command: celery -A FutureFish worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/future_fish
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=FutureFish.settings
    depends_on:
      - web
      - redis
      - db
    env_file:
      - .env
    networks:
      - future_fish_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - future_fish_network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=future_fish
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - future_fish_network

volumes:
  postgres_data:

networks:
  future_fish_network:
    driver: bridge
